### PR TITLE
Fix handling of applicative paths in equality checking for type constructors.

### PR DESCRIPTION
**Pull request by LeoTestard**

### CODE REVIEW

**Comment by LeoTestard** [comment]
Up ? cc @def-lkb

**Comment by lpw25** [comment]
Hi, thanks for the pull request.

I'm afraid I don't have time to look at this properly at the moment (maybe Fred does?), but I'm not clear what this patch is aiming to fix. I don't think the example added to the testsuite should be hitting this bit of code because their are no implicits involved so `equality_equations` should be empty.

Could you elaborate a bit? (Perhaps you have discussed this already with Fred elsewhere, but it would be good to have an explanation attached to the pull request anyway)

**Comment by let-def** [comment]
Hi,
I reviewed the patch with @LeoTestard and it looks fine to me.
The problem is that `Path.head` is called even if `equality_equations` is empty, and will fail when given applicative path.

However I won't have more time for this before end of december.

**Comment by lpw25** [comment]
> The problem is that Path.head is called even if equality_equations is empty, and will fail when given applicative path.

Ok, that makes sense. I'll go ahead an merge it.

**Pull request merged**
